name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download Source file
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Build Vuepress
        run: |
          rm -f .yarnclean yarn.lock
          yarn --non-interactive --silent
          yarn list --depth=0
          yarn run build

      - name: Upload to Qiniu
        run: |
          wget -q https://devtools.qiniu.com/qshell-v2.6.2-linux-386.tar.gz
          tar -zxvf ./qshell-v2.6.2-linux-386.tar.gz
          chmod +x ./qshell
          ./qshell account -w ${{ secrets.QINIU_ACCESSKEY }} ${{ secrets.QINIU_SECRETKEY }} github
          ./qshell listbucket hzhouse -o toupload.txt
          ./qshell batchdelete -F'\t' --force hzhouse -i toupload.txt
          ./qshell qupload2 --src-dir=./.vuepress/dist --bucket=hzhouse
          echo 'https://hzhouse.zkqiang.cn/' > torefresh.txt
          ./qshell cdnrefresh --dirs -i torefresh.txt
